### PR TITLE
[Matrix] API change update / Win UWP ssl update

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to `xbmc/xbmc#17586` and to bring in after them.

The other commit thougt for update openssl to match also 1.1.1 on UWP and add ARM64 too.

### CODE REVIEW

**Comment by aassif** [comment]
Sorry, merged by mistake.

**Comment by AlwinEsch** [comment]
NP, I create a new request :smile:

**Comment by aassif** [comment]
I need to merge the reverted branch first, right?

**Comment by AlwinEsch** [comment]
No, I create then a request only with a version increase to 2.2.5

**Comment by aassif** [comment]
OK. Thanks!

**Pull request merged**
