### PR TITLE
PVR API 7.1.0 - allow epg max future and past days

### PR DESCRIPTION
**Pull request by phunkyfish**
v6.1.0
- Update PVR API 7.1.0

Not to be merged until https://github.com/xbmc/xbmc/pull/19035 is merged.

### CODE REVIEW

**Comment by aassif** [comment]
I will support past EPG days as soon as Kodi supports them.

**Comment by aassif** [comment]
I will work on past days as soon as I merge this.

**Comment by phunkyfish** [comment]
Cool +1

**Comment by phunkyfish** [comment]
Please merge ad release when you have time. Parent PR has been merged.

**Pull request merged**
